# Generated by Django 5.0.6 on 2024-07-22 08:25

import SummarEaseApp.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SummarEaseApp", "0003_speakerdiarization_content_transcript_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerdiarization",
            name="content",
            field=SummarEaseApp.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="content",
            field=SummarEaseApp.models.JSONField(default=dict),
        ),
    ]
