# Generated by Django 5.0.6 on 2024-08-08 07:38

import ParticipantEngagement_SentimentAnalysis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("SummarEaseApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metrics",
                    ParticipantEngagement_SentimentAnalysis.models.JSONField(
                        default=dict
                    ),
                ),
                (
                    "speech_rate",
                    ParticipantEngagement_SentimentAnalysis.models.JSONField(
                        default=dict
                    ),
                ),
                (
                    "interruptions",
                    ParticipantEngagement_SentimentAnalysis.models.JSONField(
                        default=dict
                    ),
                ),
                (
                    "sentiment",
                    ParticipantEngagement_SentimentAnalysis.models.JSONField(
                        default=dict
                    ),
                ),
                (
                    "audio_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_engagement",
                        to="SummarEaseApp.audiofile",
                    ),
                ),
            ],
        ),
    ]
